export const ADD_AIRPWR = 'ADD_AIRPWR';
export const REMOVE_AIRPWR = 'REMOVE_AIRPWR';

export const ADD_EARTHPWR = 'ADD_EARTHPWR';
export const REMOVE_EARTHPWR = 'REMOVE_EARTHPWR';

export const ADD_FIREPWR = 'ADD_FIREPWR';
export const REMOVE_FIREPWR = 'REMOVE_FIREPWR';

export const ADD_WATERPWR = 'ADD_WATERPWR';
export const REMOVE_WATERPWR = 'REMOVE_WATERPWR';
